// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: RobotContainer.

#pragma once

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include <frc/smartdashboard/SendableChooser.h>
#include <frc2/command/Command.h>

#include "subsystems/Climber.h"
#include "subsystems/DriveBase.h"
#include "subsystems/Intake.h"
#include "subsystems/Shooter.h"
#include "subsystems/Tunnel.h"

#include "commands/ArcadeDrive.h"
#include "commands/AutonomousCommand.h"
#include "commands/Climb.h"
#include "commands/DriveDistance.h"
#include "commands/IntakeCargo.h"
#include "commands/RunTunnel.h"
#include "commands/Shoot.h"
#include "commands/TaxiAuto.h"
#include "commands/TankDrive.h"
#include <frc/XboxController.h>
#include <frc2/command/button/JoystickButton.h>

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

class RobotContainer {

public:

    frc2::Command* GetAutonomousCommand();
    static RobotContainer* GetInstance();

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
// The robot's subsystems
DriveBase m_driveBase;
Intake m_intake;
Shooter m_shooter;
Climber m_climber;
Tunnel m_tunnel;


frc::XboxController* getxboxController();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

private:

    RobotContainer();

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
// Joysticks
frc::XboxController m_xboxController{ControllerConstants::kXboxControllerPort};

frc::SendableChooser<frc2::Command*> m_chooser;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

AutonomousCommand m_autonomousCommand;
    static RobotContainer* m_robotContainer;

    void ConfigureButtonBindings();
};