// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

#include "commands/ArcadeDrive.h"

ArcadeDrive::ArcadeDrive(double speed, double rotation, DriveBase* m_drivebase) :
    m_speed(speed),
    m_rotation(rotation),
m_drivebase(m_drivebase)
{

    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(m_Subsystem);
    SetName("ArcadeDrive");
    AddRequirements({m_drivebase});

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

}

// Called just before this Command runs the first time
void ArcadeDrive::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void ArcadeDrive::Execute() {
    m_drivebase->ArcadeDriveFunc(m_speed, m_rotation);
}

// Make this return true when this Command no longer needs to run execute()
bool ArcadeDrive::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void ArcadeDrive::End(bool interrupted) {

}

bool ArcadeDrive::RunsWhenDisabled() const {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
}
