// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

#include "commands/IntakeCargo.h"

IntakeCargo::IntakeCargo(MotorsToRun toRun, Intake* m_intake, Tunnel* m_tunnel)
:m_toRun(toRun), m_intake(m_intake), m_tunnel(m_tunnel){

    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(m_Subsystem);
    SetName("IntakeCargo");
    AddRequirements({m_intake, m_tunnel});

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

}

// Called just before this Command runs the first time
void IntakeCargo::Initialize() {
    if (m_toRun == MotorsToRun::Wrist) {
        m_intake->MoveWristDown();
    } else if (m_toRun == MotorsToRun::Roller) {
        m_intake->Run();
    } else {
        m_intake->Run();
        m_intake->MoveWristDown();
    }
    if (m_tunnel->HasCargo()) {
        m_tunnel->RunHalfSpeed();
    }
}

// Called repeatedly when this Command is scheduled to run
void IntakeCargo::Execute() {
    if (m_tunnel->HasCargo()) {
        m_tunnel->RunHalfSpeed();
    } else {
        m_tunnel->Stop();
    }
}

// Make this return true when this Command no longer needs to run execute()
bool IntakeCargo::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void IntakeCargo::End(bool interrupted) {
    m_intake->Stop();
    m_tunnel->Stop();
    //m_intake->MoveWristUp();
    m_intake->StopWrist();
}

bool IntakeCargo::RunsWhenDisabled() const {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
}
