// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

#include "commands/Shoot.h"

Shoot::Shoot(Shooter* m_shooter, Tunnel* m_tunnel)
:m_shooter(m_shooter),
m_tunnel(m_tunnel) {

    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(m_Subsystem);
    SetName("Shoot");
    AddRequirements({m_shooter, m_tunnel});

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

}

// Called just before this Command runs the first time
void Shoot::Initialize() {
    m_shooter->Run();
    //m_tunnel->RunBackwards();
}

// Called repeatedly when this Command is scheduled to run
void Shoot::Execute() {
    if (m_shooter->AtFullSpeed()) {
        //m_tunnel->RunHalfSpeed();
    }
}

// Make this return true when this Command no longer needs to run execute()
bool Shoot::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void Shoot::End(bool interrupted) {
    m_shooter->Stop();
    m_tunnel->Stop();
}

bool Shoot::RunsWhenDisabled() const {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
}
