#include "subsystems/Tunnel.h"
#include <frc/smartdashboard/SmartDashboard.h>

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

Tunnel::Tunnel(){
    SetName("Tunnel");
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SetSubsystem("Tunnel");
    frc::SmartDashboard::PutBoolean("Subsystems/Tunnel/Running", false);

 //AddChild("motor", &m_motor);
 m_motor.SetInverted(false);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void Tunnel::Periodic() {
    // Put code here to be run every loop
}

void Tunnel::SimulationPeriodic() {
    // This method will be called once per scheduler run when in simulation

}

void Tunnel::Run() {
    m_motor.Set(kTunnelSpeed);
}

void Tunnel::RunHalfSpeed() {
    m_motor.Set(kTunnelSpeed*0.5);
}

void Tunnel::Stop() {
    m_motor.Set(0.0);
}

bool Tunnel::HasCargo() {
    return false;
    // Check IR sensor
}